# Generated by Django 4.2.11 on 2024-04-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
        ('home', '0002_testmodel'),
    ]

    operations = [
    ]
